# Generated by Django 3.0.7 on 2020-06-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20200625_1956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='T6M',
        ),
    ]
