# Generated by Django 3.0.7 on 2020-06-27 15:13

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20200627_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='H6M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
