# Generated by Django 3.0.7 on 2020-06-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_h6m'),
    ]

    operations = [
        migrations.AddField(
            model_name='t6m',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
