# Generated by Django 3.0.7 on 2020-06-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_t6m_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t6m',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
