# Generated by Django 3.0.7 on 2020-06-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20200628_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='h6m',
            name='title',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
