# Generated by Django 3.0.7 on 2020-06-28 10:33

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_h6m_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='E6M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='M6M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='S6M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sc6M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(default=' ', max_length=50)),
            ],
        ),
    ]
