# Generated by Django 3.0.7 on 2020-06-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_e6m_m6m_s6m_sc6m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select',
            name='Subject',
            field=models.CharField(choices=[('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('English', 'English'), ('Maths', 'Maths'), ('Science', 'Science'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Soical', 'Soical')], max_length=50),
        ),
    ]
